// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/trpc/:trpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trpc/[trpc]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.16.1_@parcel+watcher@2.4.1_@types+node@20.17.46_db0@0.3.1_drizzle-orm@0.31.2_@cloudfla_3bg4ecnwvcjvdk6izuor7lhene/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}