name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Install dependencies
      run: yarn install --immutable
    
    - name: Build packages
      run: yarn build
    
    - name: Run tests
      run: yarn test --watch=false --browsers=ChromeHeadless
      continue-on-error: true # Continue until tests are fully implemented
    
    - name: Check build artifacts
      run: |
        ls -la dist/
        ls -la dist/trpc-link-angular/
        if [ -d "dist/tanstack-angular-query" ]; then
          ls -la dist/tanstack-angular-query/
        fi