name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build packages
      run: yarn build
    
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn semantic-release
    
    - name: Get release version
      id: version
      run: |
        if [ -f dist/trpc-link-angular/package.json ]; then
          VERSION=$(node -p "require('./dist/trpc-link-angular/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "has_release=true" >> $GITHUB_OUTPUT
        else
          echo "has_release=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Publish trpc-link-angular to npm
      if: steps.version.outputs.has_release == 'true'
      working-directory: dist/trpc-link-angular
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Publish tanstack-angular-query to npm
      if: steps.version.outputs.has_release == 'true'
      working-directory: dist/tanstack-angular-query
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      continue-on-error: true # Continue if tanstack-angular-query fails to build